select
    SPRIDEN.SPRIDEN_ID BANNER_ID,
    SPRIDEN_LAST_NAME Last_Name,
    SPRIDEN_FIRST_NAME First_Name,
    GORADID.GORADID_ADDITIONAL_ID SUID,
    SGBSTDN.SGBSTDN_STYP_CODE Reg_Type,
    STVDEPT.STVDEPT_CODE,
    STVMAJR.STVMAJR_DESC Program_of_Study,    
    STVCLAS.STVCLAS_CODE as Student_Class
    --STVDEGC.STVDEGC_CODE Degree_Prog
    /*
    SSBSECT.SSBSECT_SUBJ_CODE Course_Subj,
    SSBSECT.SSBSECT_CRSE_NUMB Course_Numb,
    SSBSECT.SSBSECT_CRN Course_CRN,
    SSBSECT.SSBSECT_SEQ_NUMB Seq_Numb,
    SFRSTCR.SFRSTCR_GRDE_CODE Letter_Grade,
    SFRSTCR.SFRSTCR_TERM_CODE Term_Code
    
    -*/

from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202220--:parm_term_code_select.STVTERM_CODE

    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
        and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('SUS', 'EHS','UNDC','0000','VIS')
        and SGBSTDN.SGBSTDN_STST_CODE in ('AS')

    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GORADID.GORADID_ADID_CODE = 'SUID'
       /* 
    join SFRSTCR SFRSTCR on SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SFRSTCR.SFRSTCR_RSTS_CODE in ('RW', 'RE')
        and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE

    left outer join SSBSECT SSBSECT on SSBSECT.SSBSECT_CRN = SFRSTCR.SFRSTCR_CRN
        and SSBSECT.SSBSECT_TERM_CODE = STVTERM.STVTERM_CODE
     */   
    join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1
    join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1
    join STVDEPT STVDEPT on STVDEPT.STVDEPT_CODE = SGBSTDN.SGBSTDN_DEPT_CODE
    join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE)
where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null
--    and SSBSECT.SSBSECT_GMOD_CODE = 'Y'
    and exists(
        select * 
        
        from SFRSTCR SFRSTCR

        left outer join SSBSECT SSBSECT on SSBSECT.SSBSECT_CRN = SFRSTCR.SFRSTCR_CRN
        and SSBSECT.SSBSECT_TERM_CODE = STVTERM.STVTERM_CODE
        
        where 
            SFRSTCR.SFRSTCR_RSTS_CODE in ('RW', 'RE')
            and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
            and SSBSECT.SSBSECT_GMOD_CODE = 'Y'
    )
--and SFRSTCR.SFRSTCR_GRDE_CODE is not null
--and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE


--$addfilter
--$beginorder

order by
    SGBSTDN.SGBSTDN_DEPT_CODE, SGBSTDN.SGBSTDN_MAJR_CODE_1, STVCLAS.STVCLAS_CODE, SPRIDEN.SPRIDEN_LAST_NAME
--$endorder
