select
    SPRIDEN.SPRIDEN_ID BANNER_ID,
    SPRIDEN_LAST_NAME Last_Name,
    SPRIDEN_FIRST_NAME First_Name,
    GORADID.GORADID_ADDITIONAL_ID SUID,
    SGBSTDN.SGBSTDN_STYP_CODE Reg_Type,
    'N/A' as Student_Class,
    STVMAJR.STVMAJR_DESC Program_of_Study,
    STVDEGC.STVDEGC_CODE Degree_Prog,
    SSBSECT.SSBSECT_SUBJ_CODE Course_Subj,
    SSBSECT.SSBSECT_CRSE_NUMB Course_Numb,
    SSBSECT.SSBSECT_CRN Course_CRN,
    SSBSECT.SSBSECT_SEQ_NUMB Seq_Numb,
    SFRSTCR.SFRSTCR_GRDE_CODE Letter_Grade,
    SFRSTCR.SFRSTCR_TERM_CODE Term_Code

from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202220--:parm_term_code_select.STVTERM_CODE

    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
        and SGBSTDN.SGBSTDN_MAJR_CODE_1 in ('SUS')
        and SGBSTDN.SGBSTDN_STST_CODE in ('AS')

    join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GORADID.GORADID_ADID_CODE = 'SUID'
        
    join SFRSTCR SFRSTCR on SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SFRSTCR.SFRSTCR_RSTS_CODE in ('RW', 'RE')
        and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE

    left outer join SSBSECT SSBSECT on SSBSECT.SSBSECT_CRN = SFRSTCR.SFRSTCR_CRN
        and SSBSECT.SSBSECT_TERM_CODE = STVTERM.STVTERM_CODE
        
    join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1
    join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1
where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null
    
--and SFRSTCR.SFRSTCR_GRDE_CODE is not null
--and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE


--$addfilter
--$beginorder

order by
    SPRIDEN.SPRIDEN_LAST_NAME
--$endorder
