Select
    GORADID.GORADID_ADDITIONAL_ID SU_ID,
    SPRIDEN.SPRIDEN_ID Banner_ID,
    f_format_name(SPRIDEN_PIDM, 'LFMI') Full_Name,
    SHRLGPA.SHRLGPA_GPA_HOURS Cumulative_HP,
    trunc(SHRLGPA.SHRLGPA_GPA,3) Cumulative_GPA,
    STVDEGC.STVDEGC_CODE Degree_Program,
    STVDEPT.STVDEPT_DESC Department,
    STVMAJR.STVMAJR_DESC Major_Program,
    STVMAJR2.STVMAJR_DESC Minor_Program,
    STVMAJR3.STVMAJR_DESC Conc_Program,
    SHRDGMR.SHRDGMR_GRAD_DATE Degree_Post_Date,
    SGBSTDN.SGBSTDN_EXP_GRAD_DATE Expected_Grad_Date,
    SFRWDRL.SFRWDRL_EFF_WDRL_DATE Withdrawl_Date,
    CASE
        when (
            SHRDGMR.SHRDGMR_GRAD_DATE is not null
            and SHRDGMR.SHRDGMR_DEGS_CODE = 'GR'
                ) then 'Degree Posted'

         when (exists(select * from SFRWDRL SFRWDRL where SFRWDRL.SFRWDRL_PIDM = SPRIDEN.SPRIDEN_PIDM)
                ) then 'Withdrawn'
         else 'In Progress'
    END Degree_Progress

from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = :DropDown1.STVTERM_CODE
    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SGBSTDN.SGBSTDN_LEVL_CODE = 'UG'
         and SGBSTDN.SGBSTDN_STST_CODE = 'AS'
         and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)

    left outer join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
         and GORADID.GORADID_ADID_CODE = 'SUID'

    left outer join SHRLGPA SHRLGPA on SHRLGPA.SHRLGPA_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SHRLGPA.SHRLGPA_LEVL_CODE = SGBSTDN.SGBSTDN_LEVL_CODE
         and SHRLGPA.SHRLGPA_GPA_TYPE_IND = 'I'

    left outer join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM, SGBSTDN.SGBSTDN_LEVL_CODE, STVTERM.STVTERM_CODE)
    left outer join STVDEPT STVDEPT on STVDEPT.STVDEPT_CODE = SGBSTDN.SGBSTDN_DEPT_CODE
    left outer join STVDEGC STVDEGC on STVDEGC.STVDEGC_CODE = SGBSTDN.SGBSTDN_DEGC_CODE_1
    left outer join STVMAJR STVMAJR on STVMAJR.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_1
    left outer join STVMAJR STVMAJR2 on STVMAJR2.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_MINR_1
    left outer join STVMAJR STVMAJR3 on STVMAJR3.STVMAJR_CODE = SGBSTDN.SGBSTDN_MAJR_CODE_CONC_1

    left outer join SHRDGMR SHRDGMR on SHRDGMR.SHRDGMR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SHRDGMR.SHRDGMR_TERM_CODE_GRAD = STVTERM.STVTERM_CODE
        and SHRDGMR.SHRDGMR_DEGS_CODE = 'GR'

    left outer join SFRWDRL SFRWDRL on SFRWDRL.SFRWDRL_PIDM = SPRIDEN.SPRIDEN_PIDM
         and SFRWDRL.SFRWDRL_TERM_CODE = (
             select max(SFRWDRL.SFRWDRL_TERM_CODE)
             from SFRWDRL SFRWDRL2
             where SFRWDRL2.SFRWDRL_PIDM = SFRWDRL.SFRWDRL_PIDM
         )

where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null
    --and SGBSTDN.SGBSTDN_DEPT_CODE in ('CHEM', 'EFB', 'ERE', 'ESC', 'EST', 'FRM', 'LA', 'PBE', 'OA', 'OSUS' )
    and SGBSTDN.SGBSTDN_DEPT_CODE = :DropDown4.SGBSTDN_DEPT_CODE
    and STVDEGC.STVDEGC_CODE not in ('AAS')
    and exists(
        select *
        from SFRSTCR SFRSTCR
        where SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
    )

    and STVTERM.STVTERM_ACYR_CODE >= to_char(SGBSTDN.SGBSTDN_EXP_GRAD_DATE, 'yyyy')
    and to_char(SGBSTDN.SGBSTDN_EXP_GRAD_DATE, 'MM/DD/YYYY') <= ('8/31/' ||  STVTERM.STVTERM_ACYR_CODE)
    and to_char(SGBSTDN.SGBSTDN_EXP_GRAD_DATE, 'MM/YYYY') not in (12 ||'/' || STVTERM.STVTERM_ACYR_CODE)
--$addfilter

--$beginorder

order by
      --SHRDGMR.SHRDGMR_GRAD_DATE, SGBSTDN.SGBSTDN_EXP_GRAD_DATE,
      SGBSTDN.SGBSTDN_DEPT_CODE, SHRLGPA.SHRLGPA_GPA desc, SGBSTDN.SGBSTDN_MAJR_CODE_1, SPRIDEN.SPRIDEN_SEARCH_LAST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME
