SGBSTDN.SGBSTDN_EXP_GRAD_DATE >= to_date(:DropDown4.STVTERM_END_DATE) - 30
and SGBSTDN.SGBSTDN_EXP_GRAD_DATE <= to_date(:DropDown4.STVTERM_END_DATE) + 120
and exists(
       select *
       from SFRSTCR SFRSTCR
       where SFRSTCR.SFRSTCR_PIDM = SPRIDEN.SPRIDEN_PIDM
       and SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
       and SFRSTCR.SFRSTCR_RSTS_CODE in ('RE','RW'))