select  f_format_name(SPRIDEN.SPRIDEN_PIDM, 'LFMI') Student_Name, GORADID.GORADID_ADDITIONAL_ID SUID, RFRBASE.RFRBASE_FUND_TITLE,
 RPRATRM.RPRATRM_OFFER_AMT, RPRATRM.RPRATRM_ACCEPT_AMT, RPRATRM.RPRATRM_OFFER_DATE--,  rpratrm.rpratrm_accepted_amt
--SELECT * FROM RPRATRM 

from SPRIDEN SPRIDEN

     join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202240

     left outer join RPRATRM RPRATRM on RPRATRM.RPRATRM_PIDM = SPRIDEN.SPRIDEN_PIDM
          and RPRATRM.RPRATRM_TERM_CODE = STVTERM.STVTERM_CODE

     join goradid on goradid_pidm = spriden_pidm
         and GORADID_ADID_CODE = 'SUID'
         
    join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = rpratrm_pidm
         and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, RPRATRM_TERM_CODE)
         and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
         and SGBSTDN.SGBSTDN_STST_CODE = 'AS'
         and SGBSTDN.SGBSTDN_LEVL_CODE = 'GR'

join RFRBASE RFRBASE on RFRBASE_FUND_CODE = RPRATRM_FUND_CODE

join STVSTYP STVSTYP on STVSTYP.STVSTYP_CODE = SGBSTDN.SGBSTDN_STYP_CODE

join STVCLAS STVCLAS on STVCLAS.STVCLAS_CODE = f_class_calc_fnc(SGBSTDN.SGBSTDN_PIDM,SGBSTDN.SGBSTDN_LEVL_CODE, RPRATRM_TERM_CODE)
       
where 
SPRIDEN_NTYP_CODE is null
and SPRIDEN_CHANGE_IND is null
and rpratrm_aidy_code = 2122 and rpratrm_offer_amt is not null 
and goradid_additional_id = 832785498

order by
    --STVSTYP.STVSTYP_SURROGATE_ID, STVCLAS.STVCLAS_SURROGATE_ID, 
    SPRIDEN.SPRIDEN_SEARCH_LAST_NAME, RPRATRM.RPRATRM_OFFER_DATE

