/*
banner_ID,
SUID,
LNAME,
FNAME,
Pell
*/

select -- from rcrapp1
    SPRIDEN.SPRIDEN_ID BannerID,
    SPRIDEN.SPRIDEN_LAST_NAME LNAME,
    SPRIDEN.SPRIDEN_FIRST_NAME FNAME,
    RCRAPP1.RCRAPP1_SEQ_NO,
    RCRAPP2_PELL_PGI,
    ca.STAGE_CODE,
    ca.STAGE_DESC,
    SGBSTDN.SGBSTDN_STST_CODE,
    SGBSTDN.SGBSTDN_STYP_CODE,
    RPRAWRD.RPRAWRD_FUND_CODE,
    RPRAWRD.RPRAWRD_AWST_DATE,
    RPRAWRD.RPRAWRD_ACTIVITY_DATE,
    RPRAWRD_OFFER_EXP_DATE,  
    RPRAWRD_ACCEPT_AMT,  
    RPRAWRD_ACCEPT_DATE,
    RPRAWRD_PAID_AMT,
    RPRAWRD_ORIG_OFFER_AMT,
    RPRAWRD_ORIG_OFFER_DATE,
    RPRAWRD_OFFER_AMT, 
    RPRAWRD_OFFER_DATE,
    RCRAPP1_CREATE_DATE,
    RCRAPP1_ACTIVITY_DATE,
    RCRAPP1_RCPT_DATE,
    RCRAPP1_ORIG_COMP_DATE,
    RCRAPP1_PAR_US_INC,
    RCRAPP1_COMPLETION_DATE,
    RCRAPP2_INFC_CODE,
    RCRAPP2_ACTIVITY_DATE

--    select * from rcrapp2
--    r.*
    /*
    rprawrd.*,
    rcrapp1.*,
    rcrapp2.*
    */
    --sgbstdn.*


from
    SPRIDEN SPRIDEN

    join STVTERM STVTERM on STVTERM.STVTERM_CODE = 202320 --:parm_term_code_select

    left outer join RPRAWRD RPRAWRD on RPRAWRD.RPRAWRD_PIDM = SPRIDEN.SPRIDEN_PIDM
         and RPRAWRD.RPRAWRD_AIDY_CODE = STVTERM.STVTERM_FA_PROC_YR
         and RPRAWRD.RPRAWRD_FUND_CODE in ('FPELL', 'FSEOG')

    left outer join RCRAPP1 RCRAPP1 on RCRAPP1.RCRAPP1_PIDM = RPRAWRD.RPRAWRD_PIDM
         and RCRAPP1.RCRAPP1_AIDY_CODE = STVTERM.STVTERM_FA_PROC_YR
         and RCRAPP1.RCRAPP1_SEQ_NO = (
            select max(RCRAPP1_SEQ_NO)
            from RCRAPP1 r
            where r.RCRAPP1_PIDM = RPRAWRD.RPRAWRD_PIDM
            and r.RCRAPP1_AIDY_CODE = STVTERM.STVTERM_FA_PROC_YR
         )

    left outer join CALC_APPLICANT ca on ca.PIDM = SPRIDEN.SPRIDEN_PIDM
        and ca.TERM_CODE = STVTERM.STVTERM_CODE
         
    left outer join RCRAPP2 RCRAPP2 on RCRAPP2.RCRAPP2_PIDM = RPRAWRD.RPRAWRD_PIDM
        and RCRAPP2.RCRAPP2_AIDY_CODE = RCRAPP1.RCRAPP1_AIDY_CODE
        and RCRAPP2.RCRAPP2_SEQ_NO = RCRAPP1.RCRAPP1_SEQ_NO

    left outer join SGBSTDN SGBSTDN on SGBSTDN.SGBSTDN_PIDM = SPRIDEN.SPRIDEN_PIDM
        and SGBSTDN.SGBSTDN_TERM_CODE_EFF = fy_sgbstdn_eff_term(SGBSTDN.SGBSTDN_PIDM, STVTERM.STVTERM_CODE)
        and SGBSTDN.SGBSTDN_MAJR_CODE_1 not in ('0000', 'EHS', 'SUS', 'VIS')
        and SGBSTDN.SGBSTDN_STST_CODE = 'AS'

    left outer join GORADID GORADID on GORADID.GORADID_PIDM = SPRIDEN.SPRIDEN_PIDM
        and GORADID.GORADID_ADID_CODE = 'SUID'

    join RRVYAPST r on r.RRVYAPST_pidm = SPRIDEN.SPRIDEN_PIDM
        and r.RRVYAPST_AIDY_CODE = STVTERM_FA_PROC_YR
         
where
    SPRIDEN.SPRIDEN_NTYP_CODE is null
    and SPRIDEN.SPRIDEN_CHANGE_IND is null

    and (
        RPRAWRD.RPRAWRD_ACCEPT_DATE is not null
        )
        
    and (
        RCRAPP1_INFC_CODE = 'EDE'
        and RCRAPP2.RCRAPP2_INFC_CODE = RCRAPP1.RCRAPP1_INFC_CODE
        )
        
--    select * from stvterm
    --and (spriden_id = 'F00178124')
--    and aidyear = stvterm_fa_proc_yr
--    and r.term = stvterm_code

order by
      RPRAWRD.RPRAWRD_ACTIVITY_DATE desc,
      RPRAWRD.RPRAWRD_FUND_CODE, SPRIDEN.SPRIDEN_SEARCH_LAST_NAME, RPRAWRD.RPRAWRD_ACCEPT_DATE
