SFRSTCR.SFRSTCR_GRDE_CODE is not null
and SFRSTCR.SFRSTCR_TERM_CODE <= STVTERM.STVTERM_CODE

order by
    SPRIDEN.SPRIDEN_LAST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME, SSBSECT.SSBSECT_SUBJ_CODE, SSBSECT.SSBSECT_CRSE_NUMB