SFRSTCR.SFRSTCR_TERM_CODE = STVTERM.STVTERM_CODE
and SFRSTCR.SFRSTCR_GRDE_CODE = 'D'
and SGBSTDN.SGBSTDN_LEVL_CODE = 'GR'

order by
    SPRIDEN.SPRIDEN_LAST_NAME, SPRIDEN.SPRIDEN_FIRST_NAME, SSBSECT.SSBSECT_SUBJ_CODE, SSBSECT.SSBSECT_CRSE_NUMB, SSBSECT.SSBSECT_SEQ_NUMB